cloudcannon:
  data: true

sass:
  sass_dir: _sass

uploads_dir: "assets/images"

collections:
  portfolios:
    output: true

plugins:
  - jekyll-webp
  - jekyll-sitemap

webp:
  enabled: true
  quality: 75
  img_dir: ["/assets/images"]
  nested: true
  regenerate: false

icons:
  - "Facebook"
  - "Messenger"
  - "Twitter"
  - "LinkedIn"
  - "Instagram"
  - "Pinterest"
  - "YouTube"
  - "Vimeo"
  - "Dribble"
  - "Stack Overflow"
  - "Github"
  - "Email"
  - "Share"
  - "Behance"
  - "WhatsApp"

_comments:
  preview_image: A imagem que será utilizada quando compartilhando pelas redes sociais. Recomenda-se formato jpg com máximo de 600px de largura.
  text_html: Utilizar estilo destaque (bold) para as palavras que devam ser destacadas. Necessário incluir o ponto final.
  video_url: 'Usar o link de embed (i.e.: https://player.vimeo.com/video/460707024)'
  