general:
  site_url: 'https://somosbogota.tv'
  address:
  email: 'ola@somosbogota.tv'
  phone: '+55 (11) 99594-8693'
  social:
    - icon: "Instagram"
      url: 'https://www.instagram.com/somosbogota.tv/'
    - icon: "Vimeo"
      url: 'https://vimeo.com/somosbogota'
    - icon: "Facebook"
      url: 'https://www.facebook.com/somosbogota.tv'
    
branding:
  site_title: Bogotá
  nav_logo_image: /assets/graphics/logo-main-fill.svg
  footer_logo_image: /assets/graphics/logo-outline-alt.svg
  preview_image: /assets/images/preview-image.jpg
theme_settings:
  primary_color: '#d74600'
  secondary_color: '#ffcbcb'
  accent_color: '#6555ff'
  # shade_color: '#789572'
  # complementary_color: '#2f2f2f'
  font_family_embed_code_block: '<link rel="stylesheet" href="https://use.typekit.net/tyi7vla.css">'
  body_font_family: '"sofia-pro", sans-serif'
  heading_font_family: '"sofia-pro", sans-serif'
  body_font_size_number: 1.1rem
  line_height_number: 1.8
# navigation:
#   menus:
#     - name: About
#       url: /about
#       is_dropdown: false
#       submenus:
#         - name:
#           url:
#     - name: Dropdown
#       url: '#'
#       is_dropdown: true
#       submenus:
#         - name: Item 1
#           url: /
#         - name: Item 2
#           url: /
#         - name: Item 3
#           url: /
seo:
  site_description_text: Um estúdio especializado em imagens em movimento situados no meio de tudo e mais um pouco misturando linguagens e explorando caminhos e entregando no prazo.
  keywords:
configuration:
  flexbox_framework_code_block: '<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/gridlex/2.7.1/gridlex.min.css">'